server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: email-service
          uri: http://16.171.188.180:8082
          predicates:
            - Path=/api/emails/**

        - id: backend
          uri: http://13.49.132.61:8081
          predicates:
            - Path= /auth/**, /api/pizzas/**, /api/payment/**, /api/cart/**, /api/order/**, /api/user/**, /orders/** ,/outlet/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://13.49.132.61:8761/eureka/

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
