server:
  port: 8080

spring:
  application:
    name: gateway
  #  security:
  #    jwt:
  #      secret:
  #        key: a0fcbd306a451411520fb5e92f976a38fb5f587cde0b2b7894b9e120c84059baaad36ec8ec3d2bd5efc0aa021735ca631e04efdf0235b1b2a99ecfc44e87608f
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:5173"
            #              - 'https://urbanclamp.xyz'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/emails/**

        #        - id: user-service
        #          uri: lb://user-service
        #          predicates:
        #            - Path=/api/users/**, /api/roles/**, /api/addresses/**, /user-service/metrics
        #          filters:
        #            - name: AuthenticationFilter
        #              args:
        #                requiredRole: ROLE_USER
        #        - id: auth-service
        #          uri: lb://auth-service
        #          predicates:
        #            - Path=/api/auth/**, /auth-service/metrics
        #        - id: partner-service
        #          uri: lb://partner-service
        #          predicates:
        #            - Path=/api/partners/**, /api/categories/**, /api/services/**, /api/availabilities/**, /partner-service/metrics
        - id: backend
          uri: lb://backend
          predicates:
            - Path= /auth/**, /api/pizzas/**, /api/payment/**, /api/cart/**, /api/order/**, /api/user/**, /orders/**

#        - id: notification-service
#          uri: lb://notification-service
#          predicates:
#            - Path=/api/notifications/**, /notification-service/metrics

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "health,metrics,prometheus"
#  metrics:
#    export:
#      prometheus:
#        enabled: true
