package com.pizza.security;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

import com.pizza.domain.USER_ROLE;
import com.pizza.pojos.User;
import com.pizza.repository.UserRepository;

@Service
public class CustomUserDetailsService implements UserDetailsService{ //If you dont want auto password token generated by spring sec
	
	@Autowired
	private UserRepository userRepository;

	@Override
	public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
		User user=userRepository.findByEmail(username).orElse(null);
		if(user==null)
			throw new UsernameNotFoundException("User not found with given email" + username);
		
		USER_ROLE role = user.getRole();
		if(role==null)
			role = USER_ROLE.ROLE_CUSTOMER;
		
		List<GrantedAuthority> authorities=new ArrayList<>();
		
		authorities.add(new SimpleGrantedAuthority(role.toString()));
		
		return new org.springframework.security.core.userdetails.User(
				user.getEmail(),user.getPassword(),authorities);
		
	}

}
